import os
import time
import requests
import json
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import google.generativeai as genai

# --- CONFIGURATION FROM GITHUB SECSETS ---
GEMINI_KEY = os.environ.get("GEMINI_API_KEY")
BASEROW_KEY = os.environ.get("BASEROW_API_KEY")

# --- CORE SETTINGS ---
SPREADSHEET_NAME = "Business_Math_Master_Gradebook"
WORKSHEET_NAME = "Skill_Analytics"
BASEROW_URL = "https://api.baserow.io/api/database/rows/table/1012002/"

# Initialize Gemini SDK (Stable Version matching your other repos)
genai.configure(api_key=GEMINI_KEY)
model = genai.GenerativeModel('gemini-2.0-flash')

def initialize_google_sheets():
    """Authenticates using the service account file generated by GitHub Actions."""
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds = ServiceAccountCredentials.from_json_keyfile_name("service_account.json", scope)
    client = gspread.authorize(creds)
    return client.open(SPREADSHEET_NAME).worksheet(WORKSHEET_NAME)

def main():
    try:
        sheet = initialize_google_sheets()
    except Exception as e:
        print(f"Failed to connect to Google Sheets: {e}")
        return

    # Grab all data from the spreadsheet rows
    all_rows = sheet.get_all_records()
    print(f"Total rows found in sheet: {len(all_rows)}")

    # Keep track of the actual row index in Google Sheets (Row 1 is headers, so records start at Row 2)
    for index, row in enumerate(all_rows, start=2):
        status = str(row.get("Status", "")).strip()

        # Only process rows marked as Pending
        if status != "Pending":
            continue

        student_id = row.get("Student_ID", "unknown")
        math_text = row.get("Math_Text", "")
        competency = row.get("Topic_Focus", "ABM_BM11BS-Ig-1")
        strand = str(row.get("Strand_Focus", "BEC")).strip() or "BEC"

        print(f"Processing student {student_id} for competency {competency}...")

        # 1. Look up existing 4As remediation in Baserow
        headers = {"Authorization": f"Token {BASEROW_KEY}"}
        archived_lesson = ""
        try:
            search_url = f"{BASEROW_URL}?user_field_names=true&filter__field_Competency_Code__equal={competency}"
            res = requests.get(search_url, headers=headers, timeout=5).json()
            if res.get('results'): 
                archived_lesson = res['results'][0]['Lesson_Content_4As']
        except Exception as archive_err:
            print(f"Baserow lookup failed/skipped: {archive_err}")

        # 2. Build the Core AI Grading Prompt
        prompt = f"""
        Evaluate this student input for competency {competency}: "{math_text}"
        Score (0-100). If score < 75, generate a specific 4As lesson plan (### 1. Activity, ### 2. Analysis, ### 3. Abstraction, ### 4. Application) for strand {strand}.
        Respond ONLY with valid JSON: {{"score": integer, "lesson": "string"}}
        """

        # 3. Call Gemini API with a retry backup for safety
        gemini_success = False
        score, lesson, final_status = 0, "", "Needs Review"
        
        for attempt in range(3):
            try:
                response = model.generate_content(prompt, generation_config={"response_mime_type": "application/json"})
                gemini_data = json.loads(response.text)
                
                score = int(gemini_data.get("score", 0))
                lesson = gemini_data.get("lesson", "").strip()
                final_status = "Mastered" if score >= 75 else "Needs Review"
                gemini_success = True
                break
            except Exception as gemini_err:
                print(f"Gemini attempt {attempt + 1} failed: {gemini_err}. Retrying...")
                time.sleep(10)

        # 4. Determine final remediation package
        remediation_content = archived_lesson or lesson

        # 5. Find column coordinates dynamically to ensure data hits the right column
        headers_row = sheet.row_values(1)
        
        try:
            score_col = headers_row.index("Score") + 1
            remediation_col = headers_row.index("Remediation") + 1
            status_col = headers_row.index("Status") + 1
            
            if gemini_success:
                # Write results directly back into the specific student row
                sheet.update_cell(index, score_col, score)
                sheet.update_cell(index, remediation_col, remediation_content)
                sheet.update_cell(index, status_col, final_status)
                print(f"Successfully graded {student_id}. Score: {score}")
            else:
                sheet.update_cell(index, status_col, "Error Processing")
                print(f"Failed to grade {student_id} after multiple attempts.")
                
        except ValueError as cell_err:
            print(f"Column mapping error: ensure Score, Remediation, and Status exist in Row 1. {cell_err}")

        # --- THE GUARDRAIL ---
        # Forces a clean 5-second breath between student records to ensure zero rate limit penalties
        print("Cooling down for 5 seconds...")
        time.sleep(5)

    print("Batch grading process completed successfully.")

if __name__ == '__main__':
    main()
